config/routes.rb
Rails.application.routes.draw do
  get 'payment/checkout', to: 'payment#checkout', as: 'payment_checkout'
  get 'payment/failure'
  get 'payment/success', to: 'payment#success', as: 'payment_success'
  get 'payment/selected', to: 'payment#selected', as: 'payment_selected'
  get 'sessions/show'
  root 'homepage#index'
  get 'mentors/new'
  get 'mentors/edit'

  get 'sessions/create'
  get 'sessions/cancel'
  get 'sessions/approve'

  resources :mentors do
  end

  resources :catalog do
  end

  get 'homepage/index'

  devise_for :users
  resources :users do
    # modify to using match,
    # to & as for REST
    get 'profile'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mentee.rb
class Mentee < ApplicationRecord
    belongs_to :user
    has_many :sessions
    has_many :mentors, through: :sessions
end

app/models/mentor.rb
class Mentor < ApplicationRecord
    belongs_to :user
    has_one_attached :resume
    has_many :sessions
    has_and_belongs_to_many :subjects
    has_many :mentees, through: :sessions

    def addSubject(subject_name)
        subjects << Subject.find_by_name(subject_name)
    end

    def username
        user.username
    end

    def email
        user.email
    end

    def professional
        linkedin
    end

    scope :filter_by_search, -> (term) do
      @subjects = Subject.all
      @mentor_ids = []
      @subjects.each do |sub|
        if sub.name.downcase[term.downcase]
          sub.mentors.each do |mentor|
            @mentor_ids.push(mentor.id)
          end
        end
      end
      Mentor.all.each do |mntr|
        if mntr.user.username.downcase[term.downcase]
          @mentor_ids.push(mntr.id)
        end
      end
      where(id: @mentor_ids).or(where("LOWER(profile) like ?", "#{term.downcase}%"))
    end

    def self.withUserInfo
        Mentor.select('users.id AS user_id,
            users.username AS username,
            users.email AS email,
            profile,
            linkedin AS professional,
            website,
            location,
            company')
      .joins(:user);
    end

end

app/models/session.rb
class Session < ApplicationRecord
    enum status: [ :requested, :accepted, :terminated ]
    belongs_to :mentor
    belongs_to :mentee

    def self.request(mentee, mentor)
        @sess = Session.create(mentor: mentor, mentee: mentee)
        @sess.requested!
    end
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_and_belongs_to_many :mentors
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login
  has_one_attached :avatar
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def self.search(search)
      search_string = "username LIKE '%" + search + "%'" 
      users = User.where(search_string).or(User.where(email:search))
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    added_attrs = [:username, :email, :avatar, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:search] != nil and params[:search] != ""
      redirect_to catalog_path(:id => -1, :search => params[:search])
    end
    @categories = Subject.all;

  end

  def show
    if params[:search] != nil and params[:search] != ""
      @subject_name = "search " + params[:search]
      @term = params[:search]
      @mentors = Mentor.filter_by_search(@term)
    else
      id = params[:id]
      if id == "-1"
        @subject_name = "All"
        @mentors = Mentor.all
      else
        @subject = Subject.find_by_id(id)
        @subject_name = @subject.name
        @mentors = @subject.mentors
      end
    end
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :authenticate_user!

  def new
    if Mentor.find_by user: current_user
      redirect_to mentors_edit_path
    else
      @mentor = Mentor.new
      @subjects = @mentor.subjects
    end
  end

  def create
    @mentor = Mentor.new(mentor_params)

    if @mentor.save
      redirect_to catalog_index_path
    else
      render :new
    end
  end

  def edit
    @mentor = Mentor.find_by user: current_user
    @subjects = @mentor.subjects
  end
  
  def update
    @mentor = Mentor.find_by user: current_user

    if @mentor.update(mentor_params)
      redirect_to catalog_index_path
    else
      render :edit
    end
  end

  def destroy
    @mentor = Mentor.find_by user: current_user
    @mentor.destroy

    redirect_to catalog_index_path
  end

private
  def mentor_params
    ({:user => current_user, :subjects => params[:subjects].map {|name| Subject.find_by_name(name)} }).merge(params.require(:mentor).permit(:profile, :linkedin, :location, :website, :company, :resume))
  end

end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  def checkout
  end

  def failure
  end

  def success
  end

  def selected
    @plan = params[:plan]
    @price = params[:price]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user!

  def show
    @sessions_as_mentor = Session.joins(:mentor).where("mentors.user_id = ? and status < 2", current_user.id).all
    @sessions_as_mentee = Session.joins(:mentee).where("mentees.user_id = ? and status < 2", current_user.id).all
  end

  def create
    if params[:mentor_id] != nil
      # UserMailer.with(:user => current_user, :mentor => User.find_by(id:params[:mentor_id])).book_email.deliver_now
      if !(Mentee.find_by user: current_user)
        Mentee.create(user: current_user)
      end
      @mentee = Mentee.find_by user: current_user
      @mentor = Mentor.find_by user_id: params[:mentor_id]
      Session.request(@mentee, @mentor)

      redirect_to sessions_show_path
    else
      redirect_to catalog_index_path
    end
  end

  def approve
    @session = Session.find(params[:session_id])
    @session.accepted!
    redirect_to sessions_show_path
  end

  def cancel
    @session = Session.find(params[:session_id])
    @session.terminated!
    redirect_to sessions_show_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    id = params[:id]
    @user = Mentor.find_by user_id: id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/mentor_helper.rb
module MentorHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/catalog/index.html.erb
<div class="container">
  <h1 class="display-4">Mentor Match</h1>
  <p class="lead text-center">Choose a category from below to exclusively find mentors whose specializations align with your interests</p>
  <div style="margin:10px; display:flex; align-items:center; justify-content: center; margin-bottom:30px">
    <%= form_tag(catalog_index_path, method: :get) do %>
      <div class="input-group">
        <div class="form-outline" style="margin-right:5px">
          <%= text_field_tag(:search, params[:search], class:'form-control mr-sm-2', placeholder:"Search", id: "catalog_search")%>
        </div>
        <%= submit_tag "Search", class:"btn btn-outline-success my-2 my-sm-0", id: "catalog_search_button" %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-sm">
      <div class="card bg-light mb-3 p-2" style="width: 18rem; margin-left:auto; margin-right:auto;">
        <div class="card-header text-center h5 mb-2 border-0">All</div>
        <%= link_to "View", catalog_path(-1), class: "btn btn-info", id: "all_category_info_button" %>
        </div>
      </div>

    <% @categories.each_with_index do |category, index| %>
      <div class="col-sm">
        <div class="card bg-light mb-3 p-2" style="width: 18rem; margin-left:auto; margin-right:auto;">
          <div class="card-header text-center h5 mb-2 border-0"><%= category.name %></div>
            <% @id = category.name + "_category_info_button"%>
            <%= link_to "View", catalog_path(category.id), class: "btn btn-info", id: @id %>
        </div>
      </div>
    <% end %>

    <% if (@categories.length+1)%3 == 1%>
      <div class="col-sm">
        <div style="width:18rem"></div>
      </div>
      <div class="col-sm">
        <div style="width:18rem"> </div>
      </div>
    <% end %>

    <% if (@categories.length+1)%3 == 2%>
      <div class="col-sm">
        <div style="width:18rem"></div>
      </div>
    <% end %>
  </div>
</div>

app/views/catalog/show.html.erb
<div class="container">
  <h1 class="display-4">Mentors: <%=@subject_name%></h1>
  <div style="margin:10px; display:flex; align-items:center; justify-content: center;">
    <%= form_tag(catalog_index_path, method: :get) do %>
      <div class="input-group">
        <div class="form-outline" style="margin-right: 5px;">
          <%= text_field_tag(:search, params[:search], class: 'form-control mr-sm-2', placeholder: "Search", id: "catalog_search") %>
        </div>
        <%= submit_tag "Search", class:"btn btn-outline-success my-2 my-sm-0", id: "catalog_search_button" %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <% @mentors.each do |user| %>
      <% if user.user.avatar.attached? %>
        <% @img = user.user.avatar %>
      <% else %>
        <% @img = 'https://bootdey.com/img/Content/avatar/avatar7.png' %>
      <% end %>
      <div class="col-sm">
        <%= content_tag :div, class: "card", style: 'width: 18rem; margin-left: auto; margin-right: auto; margin-bottom:2rem;' do %>
          <%= image_tag @img, class: "card-img-top", alt: "card image", style: "width:18rem; object-fit: cover; object-position: center; max-height: 250px; margin-bottom: 1rem;" do %><% end %>
          <div class="card-body">
            <h5 class="card-title"><%= user.username %></h5>
            <p class="card-text">
              <%= user.profile %> <br/>
              Subjects:
              <%="#{(user.subjects.map {|sub| sub.name}).join(", ")}"%>
            </p>
            <%= link_to "More Info", user_path(user.user_id), class: "btn btn-info", id: "more_info_button" %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if @mentors.length%3 == 1%>
      <div class="col-sm">
        <div style="width:18rem; border-width:1px;"></div>
      </div>
      <div class="col-sm">
        <div style="width:18rem; border-width:1px;"> </div>
      </div>
    <% end %>

    <% if @mentors.length%3 == 2%>
      <div class="col-sm">
        <div style="width:18rem; border-width:1px;"></div>
      </div>
    <% end %>

  </div>
  <div style="display:flex; align-items:center; justify-content: center;">
    <%= link_to "View All Categories", catalog_index_path, class: "btn btn-success", id: "more_info_button_old", style: "margin: 0.5rem" %>
  </div>
</div>

app/views/homepage/index.html.erb
<div class="parallax">
    <div class="hometitle">Mentr.me</div>
    <div class="subtitle">Learn Compassionately.</div>
</div>
<div class="container">
    <div class="largespace"></div>
    <div>What is Mentr.me? Mentr.me is a platform that allows students to be mentored by an industry professional of their choice in return for a charitable donation. </div>
    <div class="largespace"></div>
    <%= render 'components/card_row', text: 'We connect recents graduates and industry professionals who have accrued job-related knowledge to students seeking their advice, generating revenue for charities you trust.', img: 'https://i.imgur.com/zmka3gC.png' %>
    <div class="space"></div>
    <%= render 'components/card_row_2', text: 'We feature public tutor profiles and advanced search functionality to allow users to handpick the perfect mentor.', img: 'https://i.imgur.com/rZ63jxw.png' %>
    <div class="space"></div>
    <%= render 'components/card_row', text: 'We take care of donation authentication to make your tutoring experience as smooth as possible.', img: 'https://i.imgur.com/Rsory0x.png' %>
    <div class="space"></div>
    <%= render 'components/card_row_2', text: 'We provide a wide variety of mentors that align with your personal experience, imbuing your charitable actions with a personal touch.', img: 'https://i.imgur.com/5TF7xQl.png' %>
    <div class="largespace"></div>
    <div class="question">Ready to learn?</div>
    <div class="explain">
        <%= link_to "Register", new_user_registration_path, :class => 'navbar-link', id: "sign_up_link"  %>
    </div>
    <div class="largespace"></div><div class="largespace"></div>
</div>

app/views/mentors/edit.html.erb
<div class="container">

    <h1 class="display-4">
        Update Mentor Profile
    </h1>
    <%= form_with model: @mentor do |f| %>
        <div class="form-group">
            <%= f.label :Introduction, class: 'h5' %><br />
            <%= f.text_area :profile, id: "profile_edit", class: 'form-control', required: true %>
        </div>

        <div class="form-group">
            <%= f.label :resume, class: 'h5 mb-1' %><br />
            <i class="text-muted">( Upload your resume! )</i>
            <% if @mentor.resume.attached? %>
                <div class="border rounded px-3 py-2 mt-2">
                    <%= f.file_field :resume, include_blank: false %>
                </div>
            <% else %>
                <div class="border rounded px-3 py-2 mt-2">
                    <%= f.file_field :resume, include_blank: false, required: true %>
                </div>
            <% end %>
            <% if @mentor.resume.attached? %>
                <div>
                    <%= link_to 'Download Resume', rails_blob_path(@mentor.resume, disposition: "attachment") %>
                </div>
            <% end %>
        </div>

        <div class="form-group">
            <%= f.label :company, class: 'h5' %><br />
            <%= f.text_field :company, id: "company_edit", class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :location, class: 'h5' %><br />
            <%= f.text_field :location, id: "location_edit", class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :website, class: 'h5' %><br />
            <%= f.text_field :website, id: "website_edit", class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :linkedin, class: 'h5' %><br />
            <%= f.text_field :linkedin, id: "linkedin_edit", class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :subjects, class: 'h5' %><br />
            <%= select_tag 'subjects[]', options_for_select(Subject.all.map{ |u| u.name }, @subjects.map{ |u| u.name }), {:multiple => :multiple, :class => 'form-control js-source-states option', :id => 'form-tags'}"%>
        </div>

        <div class="form-group">
            <%= f.submit "Save", id: "edit_mentor_profile", class: "btn btn-primary px-4" %>
        </div>
    <% end %>

    <div class="jumbotron">
        <h3>No Longer Want To Be Mentor?</h3>
        <em class="text-muted">( You can re-apply anytime! )</em>
        <p>
            <%= button_to "Quit Mentoring", mentor_path(@mentor), data: { confirm: "Are you sure?" }, method: :delete, id: "delete_mentor_account_button", class: 'btn btn-danger' %>
        </p>
    </div>

</div>

app/views/mentors/new.html.erb
<div class="container">
  <h1 class="display-4">Become A Mentor</h1>

    <%= form_with model: @mentor do |f| %>
    <div class="textarea">
        <%= f.label :profile %><br />
        <%= f.text_area :profile, id: "profile_edit", required: true, class: 'form-control'  %>
    </div>

    <div>
        (Upload your resume below!)
        <%= f.file_field :resume, class: 'form-control' %>
        <br />
    </div>

    <div class="field">
        <%= f.label :company %><br />
        <%= f.text_field :company, id: "company_edit", class: 'form-control'  %>
    </div>

    <div class="field">
        <%= f.label :location %><br />
        <%= f.text_field :location, id: "location_edit", class: 'form-control' %>
    </div>

    <div class="field">
        <%= f.label :website %><br />
        <%= f.text_field :website, id: "website_edit", class: 'form-control'  %>
    </div>

    <div class="field">
        <%= f.label :linkedin %><br />
        <%= f.text_field :linkedin, id: "linkedin_edit", class: 'form-control'  %>
    </div>

    <div class="form-group">
        <%= f.label :subjects %><br />
        <%= select_tag 'subjects[]', options_for_select(Subject.all.map{ |u| u.name }, @subjects.map{ |u| u.name }), {:multiple => :multiple, :class => 'form-control js-source-states', :id => "form-tags"} %>
    </div>


    <div class="actions">
      <%= f.submit "Sign up", id: "submit_mentor_register", class: "btn btn-primary" %>
    </div>

    <% end %>

</div>

app/views/payment/checkout.html.erb
<div class="title">Choose a collaboration plan</div>

<div class="price-table-container" style="margin-top:40px">
    <section>
        <img
            src="https://i.imgur.com/K8fBDsG.png"
            width="120"
            height="120"
        />
        <div class="name">Premium</div>
        <div class="price">$15</div>
        <div class="duration">per month</div>
        <%= link_to 'Select', payment_selected_path(:plan => "Premium", :price => 15), id: "special-plan-btn", class: 'btn btn-success' %>
    </section>
    <div style="margin-left: 150px"></div>
    <section>
        <img
            src="https://i.imgur.com/vIbh5MD.png"
            width="120"
            height="120"
        />
        <div class="name">Special</div>
        <div class="price">$5</div>
        <div class="duration">per month</div>
        <%= link_to 'Select', payment_selected_path(:plan => "Special", :price => 5), id: "special-plan-btn", class: 'btn btn-success' %>
    </section>
</div>
<div style="margin-top: 80px"></div>
<center>
    <%= link_to 'Back', edit_user_registration_path, id: "go-back-btn", class: 'btn btn-outline-secondary'%>
</center>
<div id="error-message" class="error-message"></div>

app/views/payment/failure.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Stripe Checkout Sample</title>
    <meta name="description" content="A demo of Stripe Payment Intents" />

    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="css/normalize.css" />
    <link rel="stylesheet" href="css/global.css" />
  </head>

  <body>
    <div class="togethere-background"></div>
    <div class="sr-root">
      <div class="sr-main">
        <header class="sr-header">
          <div class="sr-header__logo"></div>
        </header>
        <div class="sr-payment-summary completed-view">
          <h1>Your payment was canceled</h1>
          <button onclick="window.location.href = '/';">Restart demo</button>
        </div>
      </div>
      <div class="sr-content">
      </div>
    </div>
  </body>
</html>

app/views/payment/success.html.erb
<div class="text-center" style="margin-top:100px">
  <h1 class="display-3">Thank you for your payment!</h1>
  <p class="lead" style="margin-top:30px"><strong>Please check your email</strong> for your receipt.</p>
  <div style="margin-top:40px"/>
  <hr>
  <p style="margin-top:40px">
    Having trouble? <a href="">Contact us</a>
  </p>
  <p class="lead">
    <%= link_to 'Back to homepage', homepage_index_path, id: "back-to-homepage-btn", class: 'btn btn-primary'%>
  </p>
</div>

app/views/users/profile.html.erb
<h1><%= current_user.username %></h1>

app/views/users/show.html.erb
<!--  app/views/movies/show.html.erb -->
<div class="container">

    <div class="main-body">

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <% if @user.user.avatar.attached? %>
                      <%= image_tag @user.user.avatar, class:"rounded-circle", style:"width:10rem; height:10rem; object-fit: cover; object-position: center; "%>
                    <% else %>
                      <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <% end %>
                    <div class="mt-3">
                      <h4><%= @user.username %></h4>
                      <% if @user.company and @user.company!=""%>
                      <p class="text-secondary mb-1"><%= @user.company %></p>
                      <% end %>
                      <% if @user.location and @user.location !=""%>
                      <p class="text-muted font-size-sm"><%= @user.location %></p>
                      <% end %>
                      <%= link_to 'Request a session', sessions_create_path(:mentor_id => @user.user_id), :class => 'btn btn-info', id: "request_session_link" %>
                      <button class="btn btn-outline-info">Message</button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                    <span class="text-secondary"><%= @user.website %></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-linkedin mr-2 icon-inline"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>Linkedin</h6>
                    <span class="text-secondary"><%= @user.professional %></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><img  width="24" height="24" viewBox="0 0 24 24" src="https://img.icons8.com/dotty/80/000000/open-resume.png" class="feather feather-linkedin mr-2 icon-inline"/>Resume</h6>
                    <span class="text-secondary"><% if @user.resume.attached? %>
                      <%= link_to 'Download', rails_blob_path(@user.resume, disposition: "attachment") %>
                    <% end %> </span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-8">
              <div class="row gutters-sm">
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">primary</i>Mentorship Subjects</h6>
                      <% @user.subjects.map do |sub| %>
                        <%= sub.name %> <br/>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">personal</i>Introduction</h6>
                      <%= @user.profile %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Username</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.username %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.email %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.location %>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
        <div style="display:flex; align-items:center; justify-content: center;">
          <%= link_to "View All Mentors", catalog_index_path, class: "btn btn-success", id: "more_info_button", style: "margin: 0.5rem" %>
        </div>
    </div>